# AWS EBS will see a file named docker-compose.yml and use it to build the single container application.
version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'

# > docker-compose up